name: lint-proto-files
on: [push]
jobs:
  do-linting:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v1

    - name: run protolint
      uses: plexsystems/protolint-action@v0.2.0
