name: Generate .proto Wrapper Files
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.14.0'
    - name: Install nanopb
      run : |
        git clone https://github.com/nanopb/nanopb.git
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip install python3-protobuf
    - name: Self Checkout
      uses: actions/checkout@v2
      with:
        path: protobuf-checkout


    - name: Generate nanopb files from .proto descriptions
      run: |
        mkdir ./arduino_out
        ls -la
        protoc --plugin=./nanopb/generator/protoc-gen-nanopb --nanopb_out=./arduino_out ./protobuf-checkout/proto/wippersnapper/pin/v1/pin.proto
        ls -la arduino_out/
