name: Generate .proto Wrapper Files
#on:
#  push:
#    branches: master
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.13.0'
    - name: Install Python dependencies
      run : |
        python -m pip install --upgrade pip
        pip install protobuf
    - name: Self Checkout
      uses: actions/checkout@v2
      with:
        path: protobuf-checkout
    - name: Checkout nanopb submodule
      run: git submodule update --init --recursive --remote
    - name: Configure Git
      run: |
        git config --global user.name adafruitio
        git config --global user.email adafruitio@adafruit.com
    - name: Generate Python & JS Wrapper Files from .proto Files
      run: |
        mkdir ./python_out
        mkdir ./js_out
        ls -la
        protoc --proto_path=./protobuf-checkout/proto ./protobuf-checkout/proto/wippersnapper/*/*/*.proto --js_out=import_style=commonjs,binary:js_out --python_out=./python_out
    - name: Generate Arduino files from .proto Files
      run: |
        mkdir ./arduino_out
        ls -la
        protoc --plugin=./nanopb/generator/protoc-gen-nanopb \
        -Inanopb/generator/proto \
        --proto_path=./protobuf-checkout/proto ./protobuf-checkout/proto/wippersnapper/*/*/*.proto
        --nanopb_out=./arduino_out \
        --nanopb_opt=-I./protobuf-checkout/proto \
        --nanopb_opt=-t
    - name: Checkout Arduino Repo
      uses: actions/checkout@v2
      with:
        repository: adafruit/Adafruit_Wippersnapper_Arduino
        token: ${{ secrets.IO_BOT_PAT }}
        path: arduino-checkout
    - name: Copy Generated Arduino Files to Arduino Repo
      run: |
        rm -rf ./arduino-checkout/src/wippersnapper/
        mkdir ./arduino-checkout/src/wippersnapper/
        cp -a ./arduino_out/. ./arduino-checkout/src/
    - name: Open Arduino Pull Request
      env:
        GITHUB_USER: adafruitio
        GITHUB_TOKEN: ${{ secrets.IO_BOT_PAT }}
        PROTOBUF_BRANCH_NAME: protobuf-update
      run: |
        cd arduino-checkout
        git checkout -b $PROTOBUF_BRANCH_NAME-$GITHUB_SHA
        git status
        git add src
        git commit -m "Updating protobuf wrappers"
        hub push origin $PROTOBUF_BRANCH_NAME-$GITHUB_SHA
        hub pull-request --message ".proto file wrappers updated" --message "Auto-generated by [GitHub Actions on Protobuf Repo][1]" --message "[1]: https://github.com/adafruit/Wippersnapper_Protobuf/blob/master/.github/workflows/protoc-wrapper-generation.yml"
    - name: Checkout Python Repo
      uses: actions/checkout@v2
      with:
        repository: adafruit/Adafruit_Wippersnapper_Python
        token: ${{ secrets.IO_BOT_PAT }}
        path: python-checkout
    - name: Copy Python Files
      run: |
        rm -rf ./python-checkout/adafruit_wippersnapper/proto/
        cp -r ./python_out/ ./python-checkout/adafruit_wippersnapper/proto/
    - name: Open Python Pull Request
      env:
        GITHUB_USER: adafruitio
        GITHUB_TOKEN: ${{ secrets.IO_BOT_PAT }}
        PROTOBUF_BRANCH_NAME: protobuf-update
      run: |
        cd python-checkout
        git checkout -b $PROTOBUF_BRANCH_NAME-$GITHUB_SHA
        git add adafruit_wippersnapper
        git commit -m "Updating protobuf wrappers"
        hub push origin $PROTOBUF_BRANCH_NAME-$GITHUB_SHA
        hub pull-request --message ".proto file wrappers updated" --message "Auto-generated by [GitHub Actions on Protobuf Repo][1]" --message "[1]: https://github.com/adafruit/Wippersnapper_Protobuf/blob/master/.github/workflows/protoc-wrapper-generation.yml"
    - name: Checkout io-node Repo
      uses: actions/checkout@v2
      with:
        repository: AdafruitInternalDev/io-node
        token: ${{ secrets.IO_BOT_PAT }}
        path: js-checkout
        ref: wprsnpr # TODO: remove this when io-node@wprsnpr gets merged
    - name: Copy JS Files
      run: |
        rm -rf ./js-checkout/lib/wprsnpr/protobufs/wippersnapper/
        cp -r ./js_out/wippersnapper/ ./js-checkout/lib/wprsnpr/protobufs/wippersnapper/
    - name: Open Node Pull Request
      env:
        GITHUB_USER: adafruitio
        GITHUB_TOKEN: ${{ secrets.IO_BOT_PAT }}
        PROTOBUF_BRANCH_NAME: protobuf-update
      run: |
        cd js-checkout
        git checkout -b $PROTOBUF_BRANCH_NAME-$GITHUB_SHA
        git add lib/wprsnpr/protobufs/wippersnapper
        git commit -m "Updating protobuf wrappers"
        hub push origin $PROTOBUF_BRANCH_NAME-$GITHUB_SHA
        # TODO: remove '--base wprsnpr' when io-node@wprsnpr gets merged
        hub pull-request --base wprsnpr --message ".proto file wrappers updated" --message "Auto-generated by [GitHub Actions on Protobuf Repo][1]" --message "[1]: https://github.com/adafruit/Wippersnapper_Protobuf/blob/master/.github/workflows/protoc-wrapper-generation.yml"