name: Generate .proto Wrapper Files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.13.0'
    - run: mkdir python_out
    - run: mkdir js_out
    - run: ls -la
    - name: Generate Python & JS Files
      run: protoc --proto_path=./proto ./proto/*/*/*.proto --js_out=js_out --python_out=python_out
    - name: Open PR to WipperSnapper Python Client
      run: echo 'TODO'
    - name: Open PR to WipperSnapper Node Broker
      run: echo 'TODO'
