name: Generate .proto Wrapper Files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.13.0'
    - name: Self Checkout
      uses: actions/checkout@v2
      with:
        path: protobuf-checkout
    - name: Generate Python & JS Wrapper Files from .proto Files
      run: |
        mkdir ./python_out
        mkdir ./js_out
        ls -la
        protoc --proto_path=./protobuf-checkout/proto ./protobuf-checkout/proto/*/*/*.proto --js_out=./js_out --python_out=./python_out
    - name: Install hub
      uses: geertvdc/setup-hub@master
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Checkout Python Repo
      uses: actions/checkout@v2
      with:
        repository: adafruit/Adafruit_Wippersnapper_Python
        token: ${{ secrets.IO_BOT_PAT }}
        path: python-checkout
    - name: Copy Python Files
      run: |
        cd python-checkout
        cp -r ../python_out/* ./adafruit_wippersnapper/
    # - name: Open Python Pull Request
    #   env:
    #     GITHUB_USER: adafruitio
    #     GITHUB_TOKEN: ${{ secrets.IO_BOT_PAT }}
    #     PROTOBUF_BRANCH_NAME: protobuf-update
    #   run: |
    #     git config --global user.name adafruitio
    #     git config --global user.email adafruitio@adafruit.com
    #     cd python-checkout
    #     git checkout -b $PROTOBUF_BRANCH_NAME
    #     git add adafruit_wippersnapper
    #     git commit -m "Updating protobuf wrappers"
    #     hub push origin $PROTOBUF_BRANCH_NAME
    #     hub pull-request --message ".proto file wrappers updated" --message "Generated by https://github.com/adafruit/Wippersnapper_Protobuf/blob/master/.github/workflows/protoc-wrapper-generation.yml"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.IO_BOT_PAT }}
        commit-message: .proto file wrappers updated
        committer: AdafruitIO Bot <adafruitio@adafruit.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: protobuf-update-$GITHUB_SHA
        delete-branch: true
        title: '.proto file wrappers updated'
        body: |
          Auto-generated by [GitHub Actions on Protobuf Repo][1]

          [1]: https://github.com/adafruit/Wippersnapper_Protobuf/blob/master/.github/workflows/protoc-wrapper-generation.yml
        labels: automated pr

    - name: Open PR to WipperSnapper Node Broker
      run: echo 'TODO'
