name: Generate .proto Wrapper Files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.13.0'
    - name: Self Checkout
      uses: actions/checkout@v2
      with:
        path: protobuf-checkout
    - name: Generate Python & JS Wrapper Files from .proto Files
      run: |
        mkdir ./python_out
        mkdir ./js_out
        ls -la
        protoc --proto_path=./protobuf-checkout/proto ./protobuf-checkout/proto/*/*/*.proto --js_out=./js_out --python_out=./python_out
    - name: Install hub
      uses: geertvdc/setup-hub@master
    - name: Checkout Python, Modify Files, Open PR
      env:
        GITHUB_USER: adafruitio
        GITHUB_TOKEN: ${{ secrets.IO_BOT_PAT }}
      run: |
        hub clone adafruit/Adafruit_Wippersnapper_Python python-checkout
        cd python-checkout
        git checkout -b protobuf-update
        cp -r ../python_out/* ./adafruit_wippersnapper/
        git config --global user.name "AdafruitIO Bot"
        git config --global user.email adafruitio@adafruit.com
        git commit -am "Updating protobuf wrappers"
        hub push origin
        hub pull-request

    # - name: Checkout Python Client
    #   uses: actions/checkout@v2
    #   with:
    #     path: python-checkout
    #     repository: adafruit/Adafruit_Wippersnapper_Python
    #     ref: master
    #     token: ${{ secrets.IO_BOT_PAT }}
    # - name: Copy Python Files
    #   run: cp -r ./python_out/* ./python-checkout/adafruit_wippersnapper/
    - name: Open PR to WipperSnapper Node Broker
      run: echo 'TODO'
