name: Generate .proto Wrapper Files
on: [ push ]
  # push:
  #   branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.13.0'
    - name: Self Checkout
      uses: actions/checkout@v2
      with:
        path: protobuf-checkout
    - name: Generate Python & JS Wrapper Files from .proto Files
      run: |
        mkdir ./python_out
        mkdir ./js_out
        ls -la
        protoc --proto_path=./protobuf-checkout/proto ./protobuf-checkout/proto/*.proto --js_out=./js_out --python_out=./python_out
    - name: Configure Git
      run: |
        git config --global user.name adafruitio
        git config --global user.email adafruitio@adafruit.com
    - name: Checkout Python Repo
      uses: actions/checkout@v2
      with:
        repository: adafruit/Adafruit_Wippersnapper_Python
        token: ${{ secrets.IO_BOT_PAT }}
        path: python-checkout
    - name: Copy Python Files
      run: cp -r ./python_out/* ./python-checkout/adafruit_wippersnapper/
    - name: Open Python Pull Request
      env:
        GITHUB_USER: adafruitio
        GITHUB_TOKEN: ${{ secrets.IO_BOT_PAT }}
        PROTOBUF_BRANCH_NAME: protobuf-update
      run: |
        cd python-checkout
        git checkout -b $PROTOBUF_BRANCH_NAME-$GITHUB_SHA
        git add adafruit_wippersnapper
        git commit -m "Updating protobuf wrappers"
        hub push origin $PROTOBUF_BRANCH_NAME-$GITHUB_SHA
        hub pull-request --message ".proto file wrappers updated" --message "Auto-generated by [GitHub Actions on Protobuf Repo][1]" --message "[1]: https://github.com/adafruit/Wippersnapper_Protobuf/blob/master/.github/workflows/protoc-wrapper-generation.yml"
    # TODO:
    # - name: Open PR to WipperSnapper Arduino
    # - name: Open PR to WipperSnapper Node MQTT Broker
