name: Generate .proto Wrapper Files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.13.0'
    - name: Self Checkout
      uses: actions/checkout@v2
      with:
        path: protobuf-checkout
    - name: Generate Python & JS Wrapper Files from .proto Files
      run: |
        mkdir ./python_out
        mkdir ./js_out
        ls -la
        protoc --proto_path=./protobuf-checkout/proto ./protobuf-checkout/proto/*/*/*.proto --js_out=./js_out --python_out=./python_out
    - name: Checkout Python Client
      uses: actions/checkout@v2
      with:
        path: python-checkout
        repository: adafruit/Adafruit_Wippersnapper_Python
        ref: master
        token: ${{ secrets.IO_BOT_PAT }}
    - name: Copy Python Files
      run: cp -r ./python_out/* ./python-checkout/adafruit_wippersnapper/
    - name: Open PR to WipperSnapper Python Client
      uses: TickX/auto-cross-pr@v0.1.3
      with:
        token: ${{ secrets.IO_BOT_PAT }}
        item: python-checkout/adafruit_wippersnapper
        repo_base_branch: master
        repo_target_dir: adafruit_wippersnapper
        repo: Adafruit_Wippersnapper_Python
        repo_owner: adafruit
    - name: Open PR to WipperSnapper Node Broker
      run: echo 'TODO'
