name: Generate .proto Wrapper Files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.13.0'
    - name: Self Checkout
      uses: actions/checkout@v1
    - name: Generate Python & JS Wrapper Files from .proto Files
      run: |
        mkdir ./python_out
        mkdir ./js_out
        protoc --proto_path=./proto ./proto/*/*/*.proto --js_out=./js_out --python_out=./python_out
    - name: Checkout Python Client
      uses: actions/checkout@v2
      with:
        path: Adafruit_Wippersnapper_Python
        repository: adafruit/Adafruit_Wippersnapper_Python
        ref: master
        token: ${{ secrets.IO_BOT_PAT }}
    - name: Copy Python Files
      run: |
        cp -r ./python_out/ ./Adafruit_Wippersnapper_Python/adafruit_wippersnapper/
        cd Adafruit_Wippersnapper_Python
        git status
    - name: Open PR to WipperSnapper Python Client
      run: echo 'TODO'
    - name: Open PR to WipperSnapper Node Broker
      run: echo 'TODO'
