name: Generate wrapper files and test Arduino build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.13.0'
    - name: Install Python dependencies
      run : |
        python -m pip install --upgrade pip
        pip install protobuf
    - name: Self Checkout
      uses: actions/checkout@v2
      with:
        path: protobuf-checkout
        submodules: true
    - name: Configure Git
      run: |
        git config --global user.name adafruitio
        git config --global user.email adafruitio@adafruit.com
    - name: Checkout Arduino Repo
      uses: actions/checkout@v2
      with:
        repository: adafruit/Adafruit_Wippersnapper_Arduino
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci
    - name: Install CI-Arduino
      run: bash ci/actions_install.sh
    - name: Install Dependencies
      run: |
        pip3 install esptool
    - name: Generate Arduino files from .proto Files
      env:
        PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      run: |
        mkdir ./arduino_out
        protoc --plugin=protobuf-checkout/nanopb/generator/protoc-gen-nanopb -Iprotobuf-checkout/nanopb/generator/proto --proto_path=./protobuf-checkout/proto ./protobuf-checkout/proto/wippersnapper/*/*/*.proto --nanopb_out=./arduino_out --nanopb_opt=-I./protobuf-checkout/proto --nanopb_opt=-t
        # Local (non-CI) build command:
        # protoc --plugin=nanopb/generator/protoc-gen-nanopb -Inanopb/generator/proto --proto_path=./proto ./proto/wippersnapper/*/*/*.proto --nanopb_out=./arduino_out --nanopb_opt=-I./proto --nanopb_opt=-t
    - name: pwd
      run: pwd
    - name: list all dirs
      run: ls -d */
    - name: Copy Generated Arduino Files to Arduino Repo
      run: |
        rm -rf ./src/wippersnapper/
        mkdir ./src/wippersnapper/
        cp -a ./arduino_out/. ./src/wippersnapper
    - name: Test Feather ESP32 Build w/new .proto files
      run: python3 ci/build_platform.py feather_esp32_v2